version: '3.2'
networks:
  private:
  public:
    external:
      name: traefik_webgateway
services:
  nginx:
    image: nginx:alpine
    labels:
      - traefik.backend=${COMPOSE_PROJECT_NAME}_nginx
      - traefik.docker.network=traefik_webgateway
      - traefik.frontend.rule=Host:dev_xdebug.localhost
      - traefik.port=8080
    networks:
      - private
      - public
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ${PWD}:/var/www/
  php:
    image: jtreminio/php:7.2
    networks:
      - private
    volumes:
      - ${PWD}:/var/www
  php_xdebug:
    image: jtreminio/php:7.2
    environment:
      - PHP_DISPLAY_ERRORS=On
      - PHP_ERROR_REPORTING=-1
      - PHP_INI_SCAN_DIR=:/etc/php/conf-env/xdebug
    networks:
      - private
    volumes:
      - ${PWD}:/var/www
